<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign In</name>
   <tag></tag>
   <elementGuidId>6ab9cdba-32a5-4192-9c72-a500728b5f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signin_btn']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-content-container__2HVS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b431116e-0266-4b7b-b2da-d1c4285f8a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-content-container__2HVS</value>
      <webElementGuid>48fc3879-ebac-4c35-b261-4d6f7308c593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>07b4ad2d-d8b4-4cff-866b-704334458f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin_btn&quot;)/div[@class=&quot;btn-content-container__2HVS&quot;]</value>
      <webElementGuid>015282b0-8b5d-4117-a12c-99ad459e97e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='signin_btn']/div</value>
      <webElementGuid>9a1bced8-ff62-4a5c-aaa2-972cea5bd5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button/div</value>
      <webElementGuid>d16ea1d1-92ca-487a-9da8-b482f23bd2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>0a1978b1-d30e-4868-8f89-9d53402f5aee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
