<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KIRUBAKARAN_K</name>
   <tag></tag>
   <elementGuidId>cec4da61-1343-4a9b-a8f9-d7e22861568c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web-user-menu']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>593ca6a8-26af-420f-a16f-60701c868d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/KIRUBAKARAN_K</value>
      <webElementGuid>86b6657d-1d2a-4b73-9e89-f612e3552181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-xl font-semibold hover:text-label-1 dark:hover:text-dark-label-1 text-label-1 dark:text-dark-label-1</value>
      <webElementGuid>3bead358-c61f-47b0-ab41-f4e7af39716c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1dc45334-43dd-4907-b5c1-fc03e62e6836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>811de798-c341-404e-be5a-f3cb9ddbdd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KIRUBAKARAN_K</value>
      <webElementGuid>2c10382d-68d6-4295-858c-1297d3a10cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web-user-menu&quot;)/div[@class=&quot;relative flex w-[264px] flex-col&quot;]/div[@class=&quot;flex shrink-0 items-center  px-4 pb-4  pt-1 md:px-[1px]&quot;]/div[@class=&quot;pl-3&quot;]/a[@class=&quot;flex items-center text-xl font-semibold hover:text-label-1 dark:hover:text-dark-label-1 text-label-1 dark:text-dark-label-1&quot;]</value>
      <webElementGuid>453860ca-fa04-427a-978e-3cb85610c760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web-user-menu']/div/div/div/a</value>
      <webElementGuid>f4727389-c972-4a19-9c16-472403771dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KIRUBAKARAN_K')]</value>
      <webElementGuid>bb09e8a2-4574-419a-9c52-0dd3872aec53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/KIRUBAKARAN_K')])[2]</value>
      <webElementGuid>c04d3402-ab70-47bd-bcab-11108fb85d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/a</value>
      <webElementGuid>9549b55f-b8db-4a32-8b24-79bcefb9f69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/KIRUBAKARAN_K' and (text() = 'KIRUBAKARAN_K' or . = 'KIRUBAKARAN_K')]</value>
      <webElementGuid>e8b099da-8587-42eb-a26a-79c6f9962d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
