<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_h-full w-full rounded-full object-cover</name>
   <tag></tag>
   <elementGuidId>15faec34-131f-4fbb-85eb-1de52dab8602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navbar_user_avatar']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.h-full.w-full.rounded-full.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dbdb891d-f72e-4663-927a-fe2b4408fd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.leetcode.com/users/default_avatar.jpg</value>
      <webElementGuid>92abbd82-7ee7-43b6-bb9e-1e6e0de0a1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>ac0d318d-7d64-4a62-a817-292dda195948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-full rounded-full object-cover</value>
      <webElementGuid>f0b74292-f442-4bb1-a530-ee37b7ec5612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar_user_avatar&quot;)/img[@class=&quot;h-full w-full rounded-full object-cover&quot;]</value>
      <webElementGuid>c8c329d2-f13a-4e0c-921c-0b3463f7614f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbar_user_avatar']/img</value>
      <webElementGuid>6bc731eb-1f55-4788-ba05-3815a96d01cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>3b0e3f20-90ba-4356-ab89-646e65ae62a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2915df1c-1d59-4ad3-888e-0ed32c9f9b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.leetcode.com/users/default_avatar.jpg' and @alt = 'avatar']</value>
      <webElementGuid>43153757-6dcd-4cf6-a259-18dd127c426f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
