<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KIRUBAKARAN_K</name>
   <tag></tag>
   <elementGuidId>f70038cd-b168-49a3-8367-ccea5dad214c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web-user-menu']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7f17346-84ea-40d8-a970-c83c5b42e549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/KIRUBAKARAN_K</value>
      <webElementGuid>3cfe1ae2-3b44-41cb-801f-55ccbea1a237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center text-xl font-semibold hover:text-label-1 dark:hover:text-dark-label-1 text-label-1 dark:text-dark-label-1</value>
      <webElementGuid>c355476a-a668-4417-8745-3ba2ff209656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>66cf5847-4b33-4ca5-bf3c-f7a337152a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>129ee02f-377c-4117-8d0f-c5e0be9fb89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KIRUBAKARAN_K</value>
      <webElementGuid>6ec75831-9fd1-4430-90dd-2b3b5b75cb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web-user-menu&quot;)/div[@class=&quot;relative flex w-[264px] flex-col&quot;]/div[@class=&quot;flex shrink-0 items-center  px-4 pb-4  pt-1 md:px-[1px]&quot;]/div[@class=&quot;pl-3&quot;]/a[@class=&quot;flex items-center text-xl font-semibold hover:text-label-1 dark:hover:text-dark-label-1 text-label-1 dark:text-dark-label-1&quot;]</value>
      <webElementGuid>6ee20843-c8c9-40ff-aed8-d9dde102de4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web-user-menu']/div/div/div/a</value>
      <webElementGuid>ad6c75ba-3d8a-4fcd-9036-65539cc9e546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KIRUBAKARAN_K')]</value>
      <webElementGuid>1194c0ce-ea4a-47fd-8ca3-e3e950a7f6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/KIRUBAKARAN_K')])[2]</value>
      <webElementGuid>7b62dbe0-f599-4280-972c-476d0e72bed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/a</value>
      <webElementGuid>574b80a4-cd66-44d4-a0c8-fc20d129128b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/KIRUBAKARAN_K' and (text() = 'KIRUBAKARAN_K' or . = 'KIRUBAKARAN_K')]</value>
      <webElementGuid>58897eb9-0214-4c90-b27e-c22d295ddf67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
