<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Store_h-full w-full rounded-full object-cover</name>
   <tag></tag>
   <elementGuidId>498148c3-e4be-47ce-a70e-ef1e84273ac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navbar_user_avatar']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.h-full.w-full.rounded-full.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d5c2568e-639e-47fb-b3fd-19fd8e663423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.leetcode.com/users/default_avatar.jpg</value>
      <webElementGuid>704d62a2-31f4-4671-9972-4ef6a3ab65ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>d8bd402b-b7bc-44e0-a295-4b03814d71c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-full rounded-full object-cover</value>
      <webElementGuid>b42f8c0b-191e-4135-b8ab-2f5a72679751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar_user_avatar&quot;)/img[@class=&quot;h-full w-full rounded-full object-cover&quot;]</value>
      <webElementGuid>b3cd522d-8443-458d-9c81-883b7d993223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbar_user_avatar']/img</value>
      <webElementGuid>a8065493-242f-43d6-adba-ba25b9b2b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>e1656138-f523-46f3-891d-86bf6fa9c774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>555b136e-cb06-4c77-9e49-48ae3b8bec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.leetcode.com/users/default_avatar.jpg' and @alt = 'avatar']</value>
      <webElementGuid>022930ea-1999-4964-8b27-61e31fbfcbda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
