<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign Out</name>
   <tag></tag>
   <elementGuidId>3c890bc5-df36-41d4-a608-5da27565af0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web-user-menu']/div/ul/li[6]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2e760ab-c3de-43d2-a204-4d9a84e4fec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grow text-left</value>
      <webElementGuid>4ba7ce2d-357f-49b1-b218-4f9a1461fd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>91c705f9-50f7-4430-8d7f-4e52a4d9e199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Out</value>
      <webElementGuid>7797fb9d-6b9a-4630-9b4e-25b64b5bcb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web-user-menu&quot;)/div[@class=&quot;relative flex w-[264px] flex-col&quot;]/ul[@class=&quot;m-0  p-0 px-4 md:mt-4 md:border-none md:px-0&quot;]/li[@class=&quot;text-text-secondary dark:text-text-secondary hover:text-text-secondary dark:hover:text-text-secondary hover:bg-fill-4 dark:hover:bg-dark-fill-4 rounded cursor-pointer flex items-center py-3 space-x-6 px-2 md:space-x-3 md:py-[10px]&quot;]/div[@class=&quot;grow text-left&quot;]</value>
      <webElementGuid>f6385c70-0c54-4228-b71b-bd817a6da725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web-user-menu']/div/ul/li[6]/div[2]</value>
      <webElementGuid>1521bec8-dc59-405b-823c-1ad745051d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div[2]</value>
      <webElementGuid>e30ea3e1-51c2-40f0-9bb2-0101160f094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign Out' or . = 'Sign Out')]</value>
      <webElementGuid>c2e5a8c0-d386-4aab-bac1-7d931f06b1d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
