<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_h-full w-full rounded-full object-cover</name>
   <tag></tag>
   <elementGuidId>c9814b01-bef1-4f4a-9136-cad3e0217c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navbar_user_avatar']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.h-full.w-full.rounded-full.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc831655-b4b1-4b12-9bab-5d5172be507e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.leetcode.com/users/default_avatar.jpg</value>
      <webElementGuid>b222fd96-bce9-490d-aa43-0885fed4656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>66711347-9567-4940-b086-38291f9c98f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full w-full rounded-full object-cover</value>
      <webElementGuid>30f5de82-c575-4fed-a659-3d1a14215614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar_user_avatar&quot;)/img[@class=&quot;h-full w-full rounded-full object-cover&quot;]</value>
      <webElementGuid>c4b57ef2-2119-48c5-9421-b6a29772dabe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbar_user_avatar']/img</value>
      <webElementGuid>5f762dd7-d46e-4256-97c5-5a36f222f7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>2653352c-fd24-4ad3-bad0-daa740df26d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2ad07349-1c61-4756-b6a3-3694ddf34407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.leetcode.com/users/default_avatar.jpg' and @alt = 'avatar']</value>
      <webElementGuid>ed9a082d-172f-4555-b976-513e1bdab618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
